In [1]:
import pandas as pd
clean_01_fund_master = pd.read_csv("clean_01_fund_master.csv")
clean_02_nav_history = pd.read_csv("clean_02_nav_history.csv")
clean_03_aum_by_fund_house = pd.read_csv("clean_03_aum_by_fund_house.csv")
clean_04_monthly_sip_inflows = pd.read_csv("clean_04_monthly_sip_inflows.csv")
clean_05_category_inflows = pd.read_csv("clean_05_category_inflows.csv")
clean_06_industry_folio_count = pd.read_csv("clean_06_industry_folio_count.csv")
clean_07_scheme_performance = pd.read_csv("clean_07_scheme_performance.csv")
clean_08_investor_transactions = pd.read_csv("clean_08_investor_transactions.csv")
clean_09_portfolio_holdings = pd.read_csv("clean_09_portfolio_holdings.csv")

In [3]:
top_return = clean_07_scheme_performance.sort_values(
    "return_3yr_pct",
    ascending=False
).head(10)

top_return[
    ["scheme_name","return_3yr_pct"]
]

                                          scheme_name  return_3yr_pct
2          SBI Small Cap Fund - Regular Plan - Growth           23.39
3           SBI Small Cap Fund - Direct Plan - Growth           23.14
29             ABSL Small Cap Fund - Regular - Growth           22.38
27             Axis Small Cap Fund - Regular - Growth           20.98
17     Nippon India Small Cap Fund - Regular - Growth           20.15
39              DSP Small Cap Fund - Regular - Growth           20.08
21      Kotak Emerging Equity Fund - Regular - Growth           18.23
12           ICICI Pru Midcap Fund - Regular - Growth           18.08
38                 DSP Midcap Fund - Regular - Growth           17.16
7   HDFC Mid-Cap Opportunities Fund - Regular - Gr...           16.58

In [4]:
top_sharpe = clean_07_scheme_performance.sort_values(
    "sharpe_ratio",
    ascending=False
).head(10)

top_sharpe[
    ["scheme_name","sharpe_ratio"]
]

                                          scheme_name  sharpe_ratio
14           ICICI Pru Liquid Fund - Regular - Growth          7.68
23               Kotak Liquid Fund - Regular - Growth          6.18
30                ABSL Liquid Fund - Regular - Growth          5.14
9        HDFC Short Term Debt Fund - Regular - Growth          1.84
4        SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
19  Nippon India Gilt Securities Fund - Regular - ...          1.33
34      Mirae Asset Large Cap Fund - Regular - Growth          1.06
5           HDFC Top 100 Fund - Regular Plan - Growth          1.06
11          ICICI Pru Bluechip Fund - Direct - Growth          1.03
15     Nippon India Large Cap Fund - Regular - Growth          1.00

In [5]:
low_risk = clean_07_scheme_performance.sort_values(
    "std_dev_ann_pct"
).head(10)

low_risk[
    ["scheme_name","std_dev_ann_pct"]
]

                                          scheme_name  std_dev_ann_pct
14           ICICI Pru Liquid Fund - Regular - Growth              0.5
23               Kotak Liquid Fund - Regular - Growth              0.5
30                ABSL Liquid Fund - Regular - Growth              0.5
4        SBI Magnum Gilt Fund - Regular Plan - Growth              4.0
9        HDFC Short Term Debt Fund - Regular - Growth              4.0
19  Nippon India Gilt Securities Fund - Regular - ...              4.0
18                     Nippon India ETF Nifty 50 BeES             13.0
31         UTI Nifty 50 Index Fund - Regular - Growth             13.0
15     Nippon India Large Cap Fund - Regular - Growth             14.0
10         ICICI Pru Bluechip Fund - Regular - Growth             14.0

In [7]:
plt.scatter(
    clean_07_scheme_performance["std_dev_ann_pct"],
    clean_07_scheme_performance["return_3yr_pct"]
)

NameError: name 'plt' is not defined